trigger:
  tags:
    include:
      - 'v*'

pr: none

resources:
  repositories:
    - repository: 1ESPipelineTemplates
      type: git
      name: 1ESPipelineTemplates/1ESPipelineTemplates
      ref: refs/tags/release

extends:
  template: v1/1ES.Official.PipelineTemplate.yml@1ESPipelineTemplates
  parameters:
    pool:
      name: Azure-Pipelines-1ESPT-ExDShared
      image: windows-latest
      os: windows
    sdl:
      git: # Customize checkout to enable longpaths in git for the paralled sdl https://eng.ms/docs/cloud-ai-platform/devdiv/one-engineering-system-1es/1es-docs/1es-pipeline-templates/features/sdlanalysis/sourceanalysisstage
        longpaths: true
      sourceAnalysisPool:
        name: Azure-Pipelines-1ESPT-ExDShared
        image: windows-latest
        os: windows
    stages:
    - stage: split packages
      jobs:
      - strategy:
        matrix:
          package:
            - local_path: 'packages/abstractions'
              target_repository: 'kiota-abstractions-php'
              package_name: 'abstractions'
            - local_path: 'packages/authentication/phpleague'
              target_repository: 'kiota-authentication-phpleague-php'
              package_name: 'authentication'
            - local_path: 'packages/http/guzzle'
              target_repository: 'kiota-http-guzzle-php'
              package_name: 'http'
            - local_path: 'packages/bundle'
              target_repository: 'kiota-bundle-php'
              package_name: 'bundle'
            - local_path: 'packages/serialization/json'
              target_repository: 'kiota-serialization-json-php'
              package_name: 'serialization-json'
            - local_path: 'packages/serialization/form'
              target_repository: 'kiota-serialization-form-php'
              package_name: 'serialization-form'
            - local_path: 'packages/serialization/text'
              target_repository: 'kiota-serialization-text-php'
              package_name: 'serialization-text'
            - local_path: 'packages/serialization/multipart'
              target_repository: 'kiota-serialization-multipart-php'
              package_name: 'serialization-multipart'

      - job: packages-split
        steps:
        - checkout: self
          persistCredentials: false
          fetchDepth: 0
        - task: PowerShell@2
          displayName: 'Split package to branch'
          inputs:
            targetType: 'inline'
            script: |
              git subtree split -P $(local_path) -b release/$(package_name)
        - task: AzureKeyVault@2
          inputs:
            azureSubscription: 'Federated AKV Managed Identity Connection'
            KeyVaultName: 'akv-prod-eastus'
            SecretsFilter: 'microsoft-graph-devx-bot-appid, microsoft-graph-devx-bot-privatekey'
        - task: PowerShell@2
          displayName: 'Write private key to file'
          inputs:
            targetType: 'inline'
            script: |
              $privateKey = ConvertTo-SecureString -String $(microsoft-graph-devx-bot-privatekey) -AsPlainText -Force
              $privateKey | Out-File -FilePath microsoft-graph-devx-bot-privatekey.pem
        - task: PowerShell@2
          displayName: 'Generate GitHub App Installation token'
          inputs:
            targetType: 'inline'
            script: |
              $token = ./scripts/Generate-GitHub-Token.ps1 -AppId $(microsoft-graph-devx-bot-appid) -PrivateKeyPath microsoft-graph-devx-bot-privatekey.pem' -Repository microsoft/$(target_repository)
              Write-Host "##vso[task.setvariable variable=gh_installation_token;isOutput=true;isSecret=true]$token"
        - task: PowerShell@2
          displayName: 'Create Pull Request in Target Repository'
          inputs:
            targetType: 'inline'
            script: |
              git checkout release/$(package_name)
              git remote add release/$(package_name) https://x-access-token:$(gh_installation_token)@github.com/microsoft/$(target_repository).git
              git push -u $(package_name) release/$(package_name)
